/*	relay_xdr.c
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "relay.h"

/* FUNICÓN DE CANONIZACIÓN DE DATOS.
 * xdr_cadena:
 * TOMA UN 'cadena *' Y LO TRANSFORMA EN
 * 'XDR *'.
 * DEVUELVE:
 * 	TRUE 	EN CASO DE EXITO
 * 	FALSE 	SI HUBO ERROR
 **/
bool_t
xdr_cadena (XDR *xdrs, cadena *objp)
{
	register int32_t *buf;
	
	/* FUNCIÓN DE CANONIZACIÓN DE DATOS: xdr_string
	 * VER ARCHIVO: /usr/include/rpc/xdr.h
	 *
	 * OPERADOR UNARIO DE COMPLEMENTO A UNO: ~
	 */
	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

/* FUNICÓN DE CANONIZACIÓN DE DATOS.
 * xdr_manda_1_argument:
 * TOMA UN 'manda_1_argument *' Y LO TRANSFORMA EN
 * 'XDR *'.
 * DEVUELVE:
 * 	TRUE 	EN CASO DE EXITO
 * 	FALSE 	SI HUBO ERROR
 */
bool_t
xdr_manda_1_argument (XDR *xdrs, manda_1_argument *objp)
{
	 if (!xdr_cadena (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
/*	relay_xdr.c */
