/*	relay_server.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "relay.h"

char msg[SIZE];	/* <·· agregado */

void *
manda_1_svc(cadena arg1, cadena arg2,  struct svc_req *rqstp)
{	    /*HOST*/      /*MSG*/      /*SOLICITUD RPC*/
	static char * result;

	/*
	 * insert server code here
	 */
	fprintf(stdout,"[manda_1_svc]···\t");	/* <·· agregado */
	/*msg = arg2;	TIPOS INCOMPATIBLES	* <·· agregado */
	strcpy(msg, arg2);			/* <·· agregado */

	return (void *) &result;
}

cadena *
retira_1_svc(cadena arg1,  struct svc_req *rqstp)
{	     /*HOST*/	   /*SOLICITUD RPC*/
	static cadena  result;

	/*
	 * insert server code here
	 */
	fprintf(stdout, "···[retira_1_svc]\n");	/* <·· agregado */
	if( msg != NULL )			/* <·· agregado */
		result = msg;			/* <·· agregado */
	else					/* <·· agregado */
	{					/* <·· agregado */
		fprintf(stderr, "ERROR: BAD MESSAGE\n");/* <·· agregado */
		exit(4);			/* <·· agregado */
	}					/* <·· agregado */
	return &result;
}
/*	relay_server.c */
