/*	relay_svc.c
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "relay.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void *
_manda_1 (manda_1_argument *argp, struct svc_req *rqstp)
{         /* HOST Y MSG */	  /*  SOLICITUD RPC */

	/* VER EN relay_server.c 
	 * FUNCIÓN: manda_1_svc	 */
	return (manda_1_svc(argp->arg1, argp->arg2, rqstp));
}			      /*HOST*/      /*MSG*/

static cadena *
_retira_1 (cadena  *argp, struct svc_req *rqstp)
{	   /*HOST*/	  /*  SOLICITUD RPC */

	/* VER EN relay_server.c 
	 * FUNCIÓN: retira_1_svc */
	return (retira_1_svc(*argp, rqstp));
}			  /*HOST*/

static void
relay_1(struct svc_req *rqstp, register SVCXPRT *transp)
{	/*  SOLICITUD RPC  */  /*MANIPULADOR DEL TRANSPORTE*/
			       /*DEL LADO DEL SERVIDOR	   */
	union {
		manda_1_argument manda_1_arg; 	/*SERVER_HOST Y MSG*/
		cadena retira_1_arg;		/*DESTINATION_HOST*/
	} argument;
	char *result;
	
	/* ARGUMENTOS Y VALOR RETORNO CANONIZADOS
	 * EN FORMATO DE REPRESENTACIÓN EXTERNA DE DATOS
	 * 
	 * VER: /usr/include/rpc/
	 */
	xdrproc_t   _xdr_argument,   _xdr_result;
		    /*HOST Y MSG*/   /* MSG */
		    /*     Y    */
		    /*   HOST   */

	char *(*local)(char *, struct svc_req *);
	/* local 
	 * PUNTERO A UNA FUNCIÓN LOCAL, PERTENECIENTE AL SERVIDOR.
	 * ARGUMENTOS QUE TOMA ESA FUNCIÓN:    
	 * 	- char *
	 * 	- struct svc_req *
	 * VALOR DEVUELTO POR ESA FUNCIÓN:
	 * 	- char *
	 * 
	 * VER ARCHIVO: relay_server.c
	 * SIMILITUD CON: retira_1_svc
	 */
	
	/* SOLICITUD DE SERVICIO RPC
	 * VER: /usr/include/rpc/svc.h  ESTÁ DECLARADA LA
	 * struct svc_req {
	 * 	rpcprog_t rq_prog;		// service program number
	 * 	rpcvers_t rq_vers;		// service protocol version
	 *···> 	rpcproc_t rq_proc;		// the desired procedure
	 * 	struct opaque_auth rq_cred;    	// raw creds from the wire
	 * 	caddr_t rq_clntcred;		// read only cooked cred
	 * 	SVCXPRT *rq_xprt;		// associated transport
	 * };
	 **/     /*PROCEDIMIENTO*/
	switch ( rqstp->rq_proc ) { /*SEGÚN SEA EL PROCEDIMIENTO SOLICITADO*/
	case NULLPROC:
		/* LLAMADA A RUTINA DE ATENCIÓN PARA ENVIAR RESULTADOS DE 
		 * UNA LLAMADA A PROCEDIMIENTO REMOTO
		 */
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;
	
	/* CASO EN QUE EL PROCEDIMIENTO SOLICITADO ES: manda */
	case manda:
		_xdr_argument = (xdrproc_t) xdr_manda_1_argument; /*VER: relay_xdr.c */
		_xdr_result = (xdrproc_t) xdr_void;
		
		local = (char *(*)(char *, struct svc_req *)) _manda_1; /* VER MAS ARRIBA */
		/* ASIGNA AL PUNTERO A FUNCION 'local' LA DIRECCIÓN
		 * DE LA FUNCIÓN '_manda_1' APLICÁNDOLE UN CAST PARA 
		 * LOGRAR CONCORDANCIA EN SUS PROTOTIPOS
		 */
		break;

	/* CASO EN QUE EL PROCEDIMIENTO SOLICITADO ES: retira */
	case retira:
		_xdr_argument = (xdrproc_t) xdr_cadena; /* VER: relay_xdr.c */
		_xdr_result = (xdrproc_t) xdr_cadena;   /* VER: relay_xdr.c */
		
		local = (char *(*)(char *, struct svc_req *)) _retira_1;
		/* ASIGNA AL PUNTERO A FUNCION 'local' LA DIRECCIÓN
		 * DE LA FUNCIÓN '_retira_1' APLICANDOLE UN CAST PARA 
		 * LOGRAR CONCORDANCIA EN SUS PROTOTIPOS
		 */
		break;

	/* CASO EN QUE EL PROCEDIMIENTO SOLICITADO ES: CUALQUIER OTRA COSA */
	default:
		/* LLAMADA A UNA RUTINA DE ATENCIÓN DE SERVICIOS QUE NO IMPLANTA 
		 * EL NÚMERO DE PROCEDIMIENTO QUE SOLICITA EL INVOCADOR
		 **/
		svcerr_noproc (transp);
		return;
	}
	
	/*PONE 'sizeof (argument)' BYTES CON EL VALOR '0' 
	 * EN LA ZONA DE MEMORIA  '(char *)&argument'
	 */
	memset ((char *)&argument, 0, sizeof (argument));
	
	/*Una macro que decodifica los argumentos de una petición RPC asociada
	 * con la asa de transporte de un servicio  RPC 'transp'.
	 * El  parámetro '(caddr_t) &argument' es la dirección donde se colocarán
	 * los argumentos. '(xdrproc_t) _xdr_argument' es la rutina XDR usada 
	 * para decodificar los argumentos. Esta rutina devuelve 1 si la 
	 * decodificación tiene éxito y cero en caso contrario.*/	
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	
	/*INVOCA A LA FUNCIÓN '*local' APUNTADA POR 'local' */ 
	result = (*local)( (char *)&argument , rqstp );
	
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	/* svc_freeargs:
	 * Macro que libera cualquier dato reservado por el sistema RPC/XDR cuando
	 * decodificó los argumentos a un procedimiento de servicio usando svc_getargs().*/
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RELAY, VRELAY);

	/*CREA SERVIDOR RPC USANDO PROTOCOLO IP - SUBPROTOCOLO UDP */
	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}

	/* svc_register:
	 * 
	 * Asocia 'RELAY' y 'VRELAY' con 
	 * el procedimiento de atención de servicio, 'relay_1'. 
	 * 
	 * Se establece una correspondencia entre la terna
	 * '[RELAY, VRELAY, IPPROTO_UDP]' y 'transp->xp_port' con el servicio
	 * portmap local.
	 * La rutina svc_register() devuelve uno en caso de éxito 
	 * y cero en caso contrario.
	 */
	if (!svc_register(transp, RELAY, VRELAY, relay_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RELAY, VRELAY, udp).");
		exit(1);
	}

	/*CREA SERVIDOR RPC USANDO PROTOCOLO IP - SUBPROTOCOLO TCP */
	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RELAY, VRELAY, relay_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RELAY, VRELAY, tcp).");
		exit(1);
	}

	/* ESPERA POR PETICIONES RPC. CUANDO RECIBE UNA LA ATIENDE 
	 * MEDIANTE LA RUTINA 'relay_1'
	 */
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");//SI svc_run RETORNA HAY ERROR
	exit (1);
	/* NOTREACHED */
}
/*	relay_svc.c */
