/*	relay_clnt.c
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "relay.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
manda_1(cadena arg1, cadena arg2,  CLIENT *clnt)
{	/*HOST*/	/*MSG*/
	manda_1_argument arg;//ARGUMENTOS A CANONIZAR
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;	//HOST
	arg.arg2 = arg2;	//MSG
	
	/* LLAMADA A PROCEDIMIENTO REMOTO: manda
	 * VER ARCHIVO: relay_svc.c
	 */
	if (clnt_call (clnt, manda, (xdrproc_t) xdr_manda_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	fprintf(stdout, "[manda_1]···\t");	/* <·· agregado */	
	return ((void *)&clnt_res);
}

cadena *
retira_1(cadena arg1,  CLIENT *clnt)
{	 /*HOST*/
	static cadena clnt_res;
	
	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	
	/* LLAMADA A PROCEDIMIENTO REMOTO: retira
	 * VER ARCHIVO: relay_svc.c
	 */
	if (clnt_call (clnt, retira,
		(xdrproc_t) xdr_cadena, (caddr_t) &arg1,
		(xdrproc_t) xdr_cadena, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	fprintf(stdout,"···[retira_1]\n");	/* <·· agregado */
	return (&clnt_res);
		/*&MSG*/
}
/*	relay_clnt.c */
