/*	relay_client.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "relay.h"

/* (3) AGREGADOS LOS ARGUMENTOS: 'msg' y 'destinationhost' */
void
relay_1(char * serverhost , char * destinationhost, char * msg)
{
	CLIENT *clnt;
	void  *result_1;
	cadena manda_1_arg1 = serverhost;	//SERVER_HOST
	cadena manda_1_arg2 = msg;		//MSG_ENVIAR
	cadena  *result_2;			//MSG_RECIBIR
	cadena retira_1_arg1 = destinationhost;	//DESTINATION_HOST

#ifndef	DEBUG
	//CREA CLIENTE RPC
	clnt = clnt_create (serverhost, RELAY, VRELAY, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (serverhost);
		exit (1);
	}
#endif	/* DEBUG */
	
	//LLAMADA A PROCEDIMIENTO REMOTO: manda_1
	//VER ARCHIVO: relay_clnt.c
	result_1 = manda_1(manda_1_arg1, manda_1_arg2, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	//LLAMADA A PROCEDIMIENTO REMOTO: retira_1
	//VER ARCHIVO: relay_clnt.c
	result_2 = retira_1(retira_1_arg1, clnt);
	if (result_2 == (cadena *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	fprintf(stdout, "MENSAJE: \n %s \n", *result_2 ); /*<·· agregado */
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{

	if (argc < 3 || argc > 3) {
		printf ("usage:  %s  server_host  destination_host \n", argv[0]);
		exit (1);
	}
	
	char * serverhost;
	char * destinationhost;
	/* 2da IMPLEMENTACIÓN: MSG_ENVIAR LO LEE DE STDIN
	 * LO GUARDA EN UN BUFFER TEMPORAL Y LO ENVÍA   */
	char msg[SIZE]; 
	
	if( argv[1] != NULL )
		serverhost = argv[1];
	else
	{
		fprintf(stderr, "ERROR: BAD SERVER_HOST!!!\n");
		exit(2);
	}
	if( argv[2] != NULL )
		destinationhost = argv[1];
	else
	{
		fprintf(stderr, "ERROR: BAD DESTINATION_HOST!!!\n");
		exit(2);
	}
	
	fprintf(stdout, "INTRODUZCA EL MENSAJE A ENVIAR:\n");
	if( fgets(msg, SIZE, stdin) == NULL )
	{
		fprintf(stderr, "ERROR: BAD MESSAGE!!!\n");
		exit(2);
	}
	relay_1 (serverhost, destinationhost, msg);
	/* (1)AGREGADO: ARGUMENTO 'msg' */
	/* (2)AGREGADO: ARGUMENTO 'destinationhost' */
exit (0);
}
/*	relay_client.c */
